# Generated by Django 5.0.6 on 2024-05-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0523_alter_multiuseinvite_subscribe_to_default_streams_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="translated_content",
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="translated_content",
            field=models.JSONField(null=True),
        ),
    ]
