# Generated by Django 5.0.6 on 2024-05-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0524_archivedmessage_translated_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="archivedmessage",
            name="prefer_language",
            field=models.TextField(default="en"),
        ),
        migrations.AddField(
            model_name="message",
            name="prefer_language",
            field=models.TextField(default="en"),
        ),
    ]
